### PR TITLE
Include the NTFS Boot Record backup in the cloned image

### PR DESCRIPTION
**Pull request by pfrouleau**
Include the NTFS Boot Record backup in the cloned image

This one depends on your view. A NTFS file system is 1 block smaller than the partition and a copy of the Boot Record is stored in the last sector of the partition. When we clone a NTFS file system, this extra block is not cloned. However, that block is created/modified by mkfs.ntfs, so it seem logical to include it in the image.

This commit update the code to include the extra block in the clone, by increasing the totalblock count and setting the last bit of the bitmap. This have the following effect: the restored file system have the same checksum than the original one. And if we restore the image on a partition with identical geometry than the original, we do not need to run ntfsfixboot.

### CODE REVIEW

**Comment by pfrouleau** [comment]
Hi @Thomas-Tsai,

it seems this pull request has not been merged into Partclone. I think it could fix the issue described in this thread:
https://forums.linuxmint.com/viewtopic.php?p=1891126#p1891126
(See the section about the 8GB partition at the bottom)

Maybe I should create a new pull request. This one is very old.

**Comment by shasheene** [comment]
Further references:

Description on the partclone-utils project for mounting partclone images: https://sourceforge.net/p/partclone-utils/tickets/3/
and also relevant is this comment from on a partclone-utils fork: https://github.com/prekageo/partclone-utils/issues/2#issuecomment-731504459

**Comment by shasheene** [comment]
> Maybe I should create a new pull request. This one is very old.

@pfrouleau, no need to create a new PR. Instead you very easily "rebase" your change onto the latest partclone git commit, then update this Pull Request.

On your pull request I have tested the following instructions (except the sanity check and push step) and it works fine:

```
# Add this git respository as a remote
git remote add upstream https://github.com/Thomas-Tsai/partclone
git fetch upstream
git checkout review/include_NTFS_backup_boot_sector_in_the_image
# Apply your change on the latest partclone
git rebase upstream/master

# Sanity check your changes still solve the issue, update the git commit message if necessary

# Push your changes to your GitHub fork to the correct remote branch. This will automatically update this Pull Request
git push origin review/include_NTFS_backup_boot_sector_in_the_image
```

**Comment by pfrouleau** [comment]
@shasheene Thanks for pointing out the rebase, but I am "The git guy" at work. 😉 It is just that I am not used to Github. I manage our own server on-premise. I forgot the MR would be updated if I rebased my branch. And on a side note, I prefer to use '--force-with-lease' instead of '--force' itself. And since git 2.30, we now have '--force-if-includes'.

I had to amend my previous commit to get the code to compile after the rebase on `master`. pc_set_bit() got a new parameter in the meantime.

**Pull request merged**
