### PR TITLE
Partly revert 2d1ee7c94 fixing partclone.image to not capture zero si…

### PR DESCRIPTION
**Pull request by Sebastian-Roth**
…ze images

### CODE REVIEW

**Comment by Sebastian-Roth** [comment]
@Thomas-Tsai Not sure if you saw my comment in commit 2d1ee7c94 yet. I am working for the FOG project imaging team and we ran into issue with `partclone.image` would only capture zero size **empty** images with partclone 0.3.x versions since the above mentioned commit.

We use this simple fix in our current code but I am not sure if it has other drawbacks. Would you have a look at this?

**Comment by Thomas-Tsai** [comment]
sorry for the reply late, and i need to check bt mode before i merge the code.

**Comment by Sebastian-Roth** [comment]
@Thomas-Tsai Thanks for getting back and taking a look! There is no hurry at all with this. Just stumbled upon it yesterday and was hoping to hear what you think of this.

**Comment by Thomas-Tsai** [comment]
after discussion, we totally forgot ' fix pip issue for dd +bt ' and just accept the patch. We hope this is work for your case, and I will keep looking the changes and make sure BT mode work well!

**Pull request merged**
