### PR TITLE
Update to btrfs-progs 5.4.1

### PR DESCRIPTION
**Pull request by boretom**
Why to version 5.4.1: it's included in the Ubuntu Focal/Linux Mint 20 so it may be stable.

Also:
- Update toolbox script to use rsync for btrfs-prog code sync. This since it involves subdirectories
- Update .gitignore to include APFS binary `src\partclone.apfs`
- Set file size for btrfs test since it failed because of a minimal size necessary

Build and tests run successfully on Linux Mint 20 (Ubuntu 20.04 Focal based)

The motivation was issue [#327 on sourceforge](https://sourceforge.net/p/clonezilla/bugs/327/) which it didn't solve :)

### CODE REVIEW

**Comment by Thomas-Tsai** [comment]
oops, we are doing the same things, I will roll back to 0.3.14 and merge your pull request first.

**Comment by boretom** [comment]
Sorry about the double-work-on @Thomas-Tsai. I just realized this morning that you updated master to 4.12 and thought I better hurry up so you wouldn't have to do the switch to 5. I was too late then.

**Comment by boretom** [comment]
@Thomas-Tsai I also got a branch with the [latest btrfs-progs v5.9](https://github.com/boretom/partclone/tree/to-btrfs-progs-5.9), not sure how current you want to go. Works as well as 5.4.1 for me but that doesn't say too much.

**Comment by Thomas-Tsai** [comment]
Actually, I just upgrade btrfs-progs to some version, and not yet fishing, so we trully appreciate your contribution.  I will test 5.4.1 first, and package it. The latest (v5.9) version could be merge and release in next version, so we can do more test. 

Thank you!

**Comment by stevenshiau** [comment]
I used this merged version Partclone 0.3.16 to take an image for Linux Mint 20 having BTRFS with compress=zstd:9 option, the image was taken successfully and later it was deployed to a VM successfully. Cool!

However, during the saving and restoring, the progress bar did not correctly shown, e.g.,
[In the beginning](https://stevenshiau.org/partclone/partclone-0.3.16/b-t1.png), when the current blocks are about 10% done, no progress bar. The status is still in 1%.

[When about 30% done](https://stevenshiau.org/partclone/partclone-0.3.16/b-t2.png), still no progress bar.

[Once all done](https://stevenshiau.org/partclone/partclone-0.3.16/b-t3.png), the progress bar suddenly went to 100%.

BTW, this Clonezilla live version I created and test with Partclone 0.3.16 is here, if you want to give it a try:

https://stevenshiau.org/clonezilla-live/2.7.0-8/

Steven

**Comment by boretom** [comment]
I did a test with a VM with a compressed and an uncompressed btrfs partition and `partclone.btrfs` only.

This issue shows up with both of these partitions, doesn't depend on if compressed or not. I'll have a look into it, maybe I messed something up.

/Thomas K

**Comment by stevenshiau** [comment]
OK, thanks.

I discussed with Thomas Tsai, and he told me the issue might be due to this patch:

https://github.com/Thomas-Tsai/partclone/pull/148

Steven

**Comment by boretom** [comment]
Ok I see that makes sense, I made a test with an ext2 partition and got the same issue with the progress bar.

I'll check if I can find the root cause for that.

/Thomas K

**Comment by boretom** [comment]
In the mentioned patch there is `    if ((stop - stop) != 0) {` on line 46. I assume that should be `    if ((stop - start) != 0) {` otherwise that's always a happy `0`.

/Thomas K.

**Comment by stevenshiau** [comment]
The weird thing is, only BTRFS has the progress issue. For other file system when running Clonezilla live 2.7.0-8, I do not see this issue.

Steven

**Comment by stevenshiau** [comment]
I was wrong. Apparently the partition I tested was too small so it ran so fast and the 100% progress was shown.  I confirmed that the progress issue exists for all file system, not only BTRFS.

Steven

**Comment by Thomas-Tsai** [comment]
Following the patch(#148), I add isnormal (commit [536bec](https://github.com/Thomas-Tsai/partclone/commit/536bec059c352061295b8dc7aa87f14e9c3b8d77))) to make sure float is not NaN and remove original (stop - stop) != 0, it looks fine with me.

**Comment by stevenshiau** [comment]
Great. Thank you very much.

Steven

**Pull request merged**
