### PR TITLE
Add german language

### PR DESCRIPTION
**Pull request by PushKK**

### CODE REVIEW

**Comment by robert-scheck** [comment]
I am sorry to say this, but to me it seems like some auto-translater like Google Translate was used for this contribution – which clearly reflects in the quality of the actual translation. As a native speaker, I'll try to provide a pull request in the next days to clean up this.

**Comment by PushKK** [comment]
Dear Robert,
Thank you for your help with Deutsch translation.
Yes, it's Google.Translate.
Best way for correct your language file - use modern file from PR#232.
Danke.

**Comment by robert-scheck** [comment]
> Yes, it's Google.Translate.

Honestly, I'm not sure what the actual benefit of such (bad) automated translations for a project is – except for just contributing.

**Comment by Thomas-Tsai** [comment]
Hi,
I also have the same concern, and I am sorry because I do not know other languages besides zh_TW. I think the PO file update the best way is confirmed by people who know that.

**Pull request merged**
