### PR TITLE
update autotools build files

### PR DESCRIPTION
**Pull request by Xeonacid**
Generated using "autoreconf -fi" to support new arch.

Current version refuses to build on RISC-V with the following error:
```text
This script, last modified 2014-03-23, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
```

Updating to the newest fixes the error.

### CODE REVIEW

**Comment by Thomas-Tsai** [comment]
Hi,

Thanks for this pull, and I will merge it later. I prefer to run some basic tests, and do you know how to set up the RISC-V environment?

**Comment by Xeonacid** [comment]
@Thomas-Tsai I'm using Arch Linux RISC-V with QEMU. You may see [this instruction](https://github.com/felixonmars/archriscv-packages/wiki/Setup-Arch-Linux-RISC-V-Development-Environment). And if you'd like, I can provide a real SiFive Unmatched board provided by [PLCT Lab](https://github.com/plctlab).

**Comment by Thomas-Tsai** [comment]
Thank you. 
I am not familiar with arch, but Debian/Ubuntu is fine. As you mentioned, I created a ubuntu RISC-V environment and got an error message. I also test your code, and the result is OK. I can run ./configure and have no errors.

**Comment by Xeonacid** [comment]
Sorry, I don't know much about how to set up a Ubuntu RISC-V QEMU environment. But our Unmatched boards have Ubuntu installations if you want.

**Pull request merged**
